# Generated by Django 5.1.1 on 2024-11-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_usuario_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='verification_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
