# Generated by Django 5.1.1 on 2024-11-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_usuario_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Administrador', 'Administrador'), ('Arrendador', 'Arrendador')], default='Estudiante', max_length=20),
        ),
    ]
