# Generated by Django 5.1.1 on 2024-11-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamiento',
            name='nombre',
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='distrito',
            field=models.CharField(choices=[('Ancón', 'Ancón'), ('Carabayllo', 'Carabayllo'), ('Comas', 'Comas'), ('Independencia', 'Independencia'), ('Los Olivos', 'Los Olivos'), ('Puente Piedra', 'Puente Piedra'), ('San Martín de Porres', 'San Martín de Porres'), ('Santa Rosa', 'Santa Rosa')], default='Ancón', max_length=50),
        ),
    ]
