# Generated by Django 5.1.1 on 2024-11-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_alojamiento_nombre_alojamiento_distrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alojamiento',
            name='distrito',
            field=models.CharField(choices=[('Ancón', 'Ancón'), ('Carabayllo', 'Carabayllo'), ('Comas', 'Comas'), ('Independencia', 'Independencia'), ('Los Olivos', 'Los Olivos'), ('Puente Piedra', 'Puente Piedra'), ('San Martín de Porres', 'San Martín de Porres'), ('Santa Rosa', 'Santa Rosa'), ('Santa Anita', 'Santa Anita')], default='Ancón', max_length=50),
        ),
    ]
