# Generated by Django 5.1.1 on 2024-11-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_usuario_facebook_url_usuario_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mostrar_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mostrar_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mostrar_tiktok',
            field=models.BooleanField(default=False),
        ),
    ]
